[webservers]
# Example: your_vm_ip ansible_user=ubuntu project_path=/home/ubuntu/ayosdocs
47.129.145.152 ansible_user=ubuntu project_path=/home/ubuntu/ayosdocs ansible_ssh_private_key_file=~/.ssh/ayosdocs-key.pem