tunnel: 30dbe7f1-3a82-4e8f-9eb9-d6667b7d63b3
credentials-file: /etc/cloudflared/creds.json

ingress:
  - hostname: test.ayosdocs.com
    service: http://localhost:80
  - hostname: ayosdocs.com
    service: http://localhost:80
  - service: http_status:404
